name: accept_language_parser
description: Parse and match HTTP `Accept-Language` header.
version: 1.0.2
homepage: https://github.com/flutter-cavalry/accept_language_parser

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  mgenware_dart_lints: ^6.5.2
  test: ^1.16.0
